# Generated by Django 2.1.2 on 2018-11-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('wishlist', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('strain', models.TextField()),
                ('ctype', models.TextField()),
                ('thc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cbd', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Product'),
        ),
        migrations.AddField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
