# Generated by Django 2.1.2 on 2018-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
