# Generated by Django 2.1.2 on 2018-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cbd',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ctype',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='strain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
