# Generated by Django 2.1.2 on 2018-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20181117_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
